### ISSUE TITLE
람다로 변환하기

### ISSUE THREAD

**Issue by adt-mgpark** [adt-hgkim/todoapp#1]
https://github.com/adt-hgkim/todoapp/blob/9bf00c5e80ce3dcda855a7d8e04c8f6f3bdd52e1/index.vue#L18-L23

함수에서 리턴할때 람다를 쓰면 이렇게 할 수 있어요 ㅎ
`
data: () => ({ input_task: ""... })
`

**Comment by adt-hgkim** [comment]
반영했습니다.
