### ISSUE TITLE
람다 2

### ISSUE THREAD

**Issue by adt-mgpark** [adt-hgkim/todoapp#4]
https://github.com/adt-hgkim/todoapp/blob/f02bcb81c4d6c2c1737e6912c107feed299540bc/index.vue#L46-L54

이것도 이런식으로 변환가능합니다.
`
.then(res => res.data.forEach(x => task.push({ id: x[0] ... }))
`

**Comment by adt-hgkim** [comment]
반영했습니다. 감사합니다.
